server:
  port: 8080
spring:
  application:
    name: cloud-payment-service
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.98.130:3306/LanDao?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 201609
  jackson:
    default-property-inclusion: non_null

#  freemarker:
#    template-loader-path: /WEB-INF/
  freemarker:
    # 设置模板后缀名
    suffix: .ftl
    # 设置文档类型
#    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: false

  # 设置静态文件路径，js,css等
  mvc:
#    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp



mybatis-plus:
   mapper-locations: classpath:mapper/*Mapper.xml
   type-aliases-package: com.lin.landao.entities


